version: '3.7'

x-setup: &setup
  build:
    context: .
  image: hangouthere/golden-hammer-service
  container_name: setup
  stdin_open: true
  tty: true
  env_file: .env
  environment:
    - NODE_ENV=development
    - NODE_OPTIONS=--enable-source-maps --trace-warnings
  command: 'tail -f /dev/null'
  user: '0'
  working_dir: '/app'

services:
  setup:
    <<: *setup
    profiles:
      - standard
    volumes:
      - .:/app
      # Volumes to act on in _setup_helper.sh
      - node_modules_chat:/_vols/1
      - node_modules_messaging:/_vols/2
      - node_modules_pubsub:/_vols/3
      # Overlays git config to avoid accessing submodules in container
      - /dev/null:/app/.git

  setup-linked:
    <<: *setup
    profiles:
      - linked
    volumes:
      - .:/app
      - ../.docker/.npmrc-localRegistry:/app/.npmrc
      # Overlays git config to avoid accessing submodules in container
      - /dev/null:/app/.git
      # Volumes to act on in _setup_helper.sh
      - node_modules_chat:/_vols/1
      - node_modules_messaging:/_vols/2
      - node_modules_pubsub:/_vols/3
    networks:
      - hh-util_registry

volumes:
  node_modules_chat:
  node_modules_messaging:
  node_modules_pubsub:

networks:
  hh-util_registry:
    external: true
