version: '3.7'

x-dev-mode: &dev-mode
  command: "sh -c 'sleep 1 && npm run withnfgutil'"
  stdin_open: true
  tty: true
  environment:
    - NODE_ENV=development
    - REQUESTTIMEOUT=0
    - NODE_OPTIONS=--enable-source-maps --trace-warnings
  volumes:
    - .:/app
    # - /app/node_modules
    - /dev/null:/app/.git # For git submodules
    - ../golden-hammer-shared:/golden-hammer-shared
    - ../../../general/nfg-util/:/nfg-util
  ports:
    - '9229:9229'

services:
  test:
    <<: *dev-mode
    restart: unless-stopped
    image: golden-hammer-service
    command: ['npm', 'run', 'test']
    ports:
      - '11111:9229'

  api:
    <<: *dev-mode
    ports:
      - '9229:9229'

  gh-pubsub:
    <<: *dev-mode
    ports:
      - '9230:9229'

  gh-messaging:
    <<: *dev-mode
    ports:
      - '9240:9229'

  twitch-chat:
    <<: *dev-mode
    ports:
      - '9241:9229'

networks:
  internal:
