version: '3.7'

x-test-mode: &test-mode
  image: hangouthere/golden-hammer-service
  command: tail -f /dev/null

services:
  api:
    <<: *test-mode
    command: npx hh-test
    # command: npx hh-test-debug
    ports:
      - '11111:9229'

  # Make sure no other service containers start, we'll run tests in `api`
  gh-pubsub:
    <<: *test-mode
  gh-messaging:
    <<: *test-mode
  twitch-chat:
    <<: *test-mode
  nats:
    <<: *test-mode
  redis:
    <<: *test-mode
  redis-gui:
    <<: *test-mode
  traefik:
    <<: *test-mode
  jaeger:
    <<: *test-mode
