version: '3.7'

x-dev-mode: &dev-mode
  command: ['npm', 'run', 'dev']
  environment:
    - NODE_ENV=development
    - REQUESTTIMEOUT=0
    - NODE_OPTIONS=--enable-source-maps --trace-warnings

services:
  api:
    <<: *dev-mode
    # volumes: # We don't mount the unnamed adhoc volume as below, because we want
    #            in-editor/lsp processing available for libs, etc.
    ##
    ports:
      - '9229:9229'

  gh-pubsub:
    <<: *dev-mode
    volumes:
      # Create unnamed adhoc volume to avoid fs collision
      - /app/node_modules
    ports:
      - '9230:9229'

  gh-messaging:
    <<: *dev-mode
    volumes:
      # Create unnamed adhoc volume to avoid fs collision
      - /app/node_modules
    ports:
      - '9240:9229'

  twitch-chat:
    <<: *dev-mode
    volumes:
      # Create unnamed adhoc volume to avoid fs collision
      - /app/node_modules
    ports:
      - '9241:9229'
