version: '3.7'

x-moleculer-microservice: &moleculer-microservice
  build:
    context: .
  image: hangouthere/golden-hammer-service
  restart: unless-stopped
  stdin_open: true
  tty: true
  user: '1000'
  env_file: .env
  volumes:
    - .:/app
    # Overlays git config to avoid accessing submodules in container
    - /dev/null:/app/.git
  depends_on:
    - nats
    - redis
    - api
  networks:
    - gh-services

services:
  api:
    <<: *moleculer-microservice
    container_name: gh-api
    depends_on:
      - nats
      - redis
    environment:
      SERVICES: api
      PORT: 3000 #TODO: Determine if we really need to specify this
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.api.rule=PathPrefix(`/`)'
      - 'traefik.http.services.api.loadbalancer.server.port=3000'

  gh-pubsub:
    <<: *moleculer-microservice
    container_name: gh-pubsub
    environment:
      SERVICES: gh-pubsub

  gh-messaging:
    <<: *moleculer-microservice
    container_name: gh-messaging
    environment:
      SERVICES: gh-messaging

  twitch-chat:
    <<: *moleculer-microservice
    container_name: gh-twitch-chat
    environment:
      SERVICES: twitch-chat

  #mongo:
  #  image: mongo:4
  #  volumes:
  #    - mongo-db:/data/db
  #  networks:
  #    - gh-services

  nats:
    image: nats:2
    networks:
      - gh-services

  redis:
    image: redis:alpine
    volumes:
      - redis_cache:/data
    networks:
      - gh-services

  redis-gui:
    image: rediscommander/redis-commander
    stdin_open: true
    tty: true
    networks:
      - gh-services
    environment:
      - REDIS_HOSTS=gh:redis:6379
    ports:
      - '8500:8081'

  traefik:
    image: traefik:v2.1
    command:
      - '--log.level=debug'
      - '--providers.docker=true'
      - '--providers.docker.exposedbydefault=false'
    ports:
      - 3000:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - gh-services
      - default

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - '9999:16686'
    volumes:
      - jaeger:/tmp
    networks:
      - gh-services

networks:
  gh-services:
    name: gh-services

volumes:
  redis_cache:
  jaeger:
#   mongo-db:
#     name: mongo-db
