version: '3.3'

services:
  api:
    command: ['npm', 'run', 'dev']
    stdin_open: true
    tty: true
    environment:
      - NODE_ENV=development
    volumes:
      - './:/app'
    ports:
      - '9229:9229'

  gh-chat:
    command: ['npm', 'run', 'dev']
    stdin_open: true
    tty: true
    environment:
      - NODE_ENV=development
    volumes:
      - './:/app'
    ports:
      - '9240:9229'

  twitch-chat:
    command: ['npm', 'run', 'dev']
    stdin_open: true
    tty: true
    environment:
      - NODE_ENV=development
    volumes:
      - './:/app'
    ports:
      - '9241:9229'
