version: '3.7'

x-moleculer-microservice: &moleculer-microservice
  build:
    context: .
  image: golden-hammer-service
  restart: unless-stopped
  stdin_open: true
  tty: true
  env_file: .env
  volumes:
    - .:/app
    # - /app/node_modules
    # Overlays git config to avoid accessing submodules in container
    - /dev/null:/app/.git
    # Include gh-shared to link in container
    - ../golden-hammer-shared:/golden-hammer-shared
  depends_on:
    - nats
    - redis
    - api
  networks:
    - internal

services:
  api:
    <<: *moleculer-microservice
    depends_on:
      - nats
      - redis
    environment:
      SERVICES: api
      PORT: 3000
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.api.rule=PathPrefix(`/`)'
      - 'traefik.http.services.api.loadbalancer.server.port=3000'

  gh-pubsub:
    <<: *moleculer-microservice
    environment:
      SERVICES: gh-pubsub

  gh-messaging:
    <<: *moleculer-microservice
    environment:
      SERVICES: gh-messaging

  twitch-chat:
    <<: *moleculer-microservice
    environment:
      SERVICES: twitch-chat

  #mongo:
  #  image: mongo:4
  #  volumes:
  #    - data:/data/db
  #  networks:
  #    - internal

  nats:
    image: nats:2
    networks:
      - internal

  redis:
    image: redis:alpine
    networks:
      - internal

  redis-gui:
    image: rediscommander/redis-commander
    stdin_open: true
    tty: true
    networks:
      - internal
    environment:
      - REDIS_HOSTS=gh:redis:6379
    ports:
      - '8500:8081'

  traefik:
    image: traefik:v2.1
    command:
      - '--providers.docker=true'
      - '--providers.docker.exposedbydefault=false'
    ports:
      - 3000:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - internal
      - default

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - '9999:16686'
    networks:
      - internal

networks:
  internal:

volumes:
  data:
