version: '3.7'

x-dev-mode: &dev-mode
  command: ['npm', 'run', 'dev:linked']
  volumes:
    - ../.docker/.npmrc-localRegistry:/app/.npmrc
  networks:
    - nfg-util_registry

services:
  api:
    <<: *dev-mode

  gh-pubsub:
    <<: *dev-mode

  gh-messaging:
    <<: *dev-mode

  twitch-chat:
    <<: *dev-mode

networks:
  internal:
  nfg-util_registry:
    external: true
