version: '3.7'

x-dev-mode: &dev-mode
  command: ['npm', 'run', 'dev']
  environment:
    - NODE_ENV=development
    - REQUESTTIMEOUT=0
    - NODE_OPTIONS=--enable-source-maps --trace-warnings

services:
  api:
    <<: *dev-mode
    ports:
      - '9229:9229'

  gh-pubsub:
    <<: *dev-mode
    ports:
      - '9230:9229'

  gh-messaging:
    <<: *dev-mode
    ports:
      - '9240:9229'

  twitch-chat:
    <<: *dev-mode
    ports:
      - '9241:9229'
